### ISSUE TITLE
Unknown permission: endowment:keyring

### ISSUE THREAD

**Issue by yulafezmesi** [MetaMask/snap-simple-keyring#129]
hey there, trying to test things out this template, however keyring permission does not recognized by extension. any idea what could causing this?

<img width='300' src='https://github.com/MetaMask/snap-simple-keyring/assets/45617686/1fa94e07-083a-4203-9e43-a13a093eb964'/>

**Comment by danroc** [comment]
Hi @yulafezmesi, sorry for the delay! The permission was merged into MetaMask and should be available now. Feel free to reopen this issue if you still face this problem.
